project:
  type: website
  output-dir: docs

website:
  title: "SS2024"
  navbar:
    right:
      - icon: github    
        href: https://github.com/guebin/SS2024
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg/playlists?view=50&sort=dd&shelf_id=2
format:
  html:
    theme: cosmo
    css: styles.css