---
title: "07wk: 측도론의 중요이론들 (2)"
author: "최규빈"
date: "10/24/2024"
reference-location: margin
citation-location: margin
cap-location: margin
draft: false
---

# 1. 강의영상 
{{< video https://youtu.be/playlist?list=PLQqh36zP38-wPRAGCBWdFBZvnPV7102DO&si=JCIBoQID_LlT4ZjK >}}

# 2. 집합함수 

## A. 집합함수의 성질 

`# 정의`: $\Omega$의 부분집합들의 모임 ${\cal A}$에서 정의된 집합함수 $\tilde{m}: {\cal A}\to [0,\infty]$에 대하여, 아래와 같은 용어를 정의하자. 

:::{.callout-note}

### additive 

함수 $\tilde{m}$이 ${\cal A}$에서 additive 하다는 것은, 

$$\text{(1)} B_1,\dots, B_n \in {\cal A} ~~\text{(2)}\biguplus_{i=1}^{n}B_i \in {\cal A}~ \Longrightarrow ~ \tilde{m}\left(\biguplus_{i=1}^{n} B_{i}\right)=\sum_{i=1}^{n}\tilde{m}(B_i)$$

이 성립한다는 의미이다. 
:::

:::{.callout-note}

### $\sigma$-additive 

함수 $\tilde{m}$이 ${\cal A}$에서 $\sigma$-additive 하다는 것은, 

$$\text{(1)} B_1,B_2,\dots \in {\cal A} ~~\text{(2)}\biguplus_{i=1}^{\infty}B_i \in {\cal A}~ \Longrightarrow ~ \tilde{m}\left(\biguplus_{i=1}^{\infty} B_{i}\right)=\sum_{i=1}^{\infty}\tilde{m}(B_i)$$

이 성립한다는 의미이다. 
:::

:::{.callout-note}

### subadditive 

함수 $\tilde{m}$이 ${\cal A}$에서 subadditive 하다는 것은, 

$$\text{(1)} A_1,\dots, A_n \in {\cal A} ~~\text{(2)}\bigcup_{i=1}^{n}A_i \in {\cal A}~ \Longrightarrow ~ \tilde{m}\left(\bigcup_{i=1}^{n} A_{i}\right)\leq\sum_{i=1}^{n}\tilde{m}(A_i)$$


이 성립한다는 의미이다. 
:::

:::{.callout-note}

### $\sigma$-subadditive 

함수 $\tilde{m}$이 ${\cal A}$에서 $\sigma$-subadditive 하다는 것은, 

$$\text{(1)}A_1,A_2,\dots \in {\cal A} ~~\text{(2)}\bigcup_{i=1}^{\infty}A_i \in {\cal A}~ \Longrightarrow ~ \tilde{m}\left(\bigcup_{i=1}^{\infty} A_{i}\right)\leq\sum_{i=1}^{\infty}\tilde{m(A_i)}$$

이 성립한다는 의미이다. 
:::

여기에서 집합열 $A_1,A_2,\dots$ 은 서로소가 아닌 집합열, $B_1,B_2,\dots$ 는 서로소인 집합열이다. 


`#` 

`-` 위의 정의에서 ${\cal A}$ 시그마필드라면, 위의 정의에서 조건 (2) 는 모두 생략할 수 있다. 

`-` 체크해볼만한 성질들이 있다. 

1. $\Omega$가 유한집합일 경우, $\sigma$-additivity와 additivity는 동일하며, $\sigma$-subadditivity와 subadditivity는 동일하다. 
2. 만약 ${\cal A}$가 세미링이라면, additivity는 sub-additivity를 암시하고 $\sigma$-additivity는 $\sigma$-subadditivity를 암시한다.


## B. 측도, 유한측도, 확률

`# (간단한) 정의` -- 측도는 정의역이 시그마필드이고 $\sigma$-additivty를 만족하는 집합함수 $m$이다. 

`# (간단한) 정의` -- $m(\Omega)=1$ 인 측도를 확률측도라고 하고, 간단히 확률이라고 줄여부르기도 한다. 

`# (간단한) 정의` -- $m(\Omega)<\infty$ 인 측도를 유한측도라고 한다. 

`-` 따라서 확률측도는 유한측도이다. 정리하면 

$$\text{prob-msr $\Rightarrow$ finite-msr $\Rightarrow$ msr}$$

이다. 

`-` 르벡메저는 유한측도가 아니다. 

## C. $\sigma$-유한측도

`# 정의` -- $(\Omega,{\cal F}, m)$ 을 측도공간이라고 하자. 아래가 성립한다면

$$\text{$\exists~ \Omega_1,\Omega_2, \dots  \in {\cal F}$ such that (1) $\cup_{i=1}^{\infty}\Omega_i=\Omega$ and (2) $\forall n \in \mathbb{N}: m(\Omega_n)< \infty$}$$ 

$m$을 $\sigma$-유한측도라고 한다. 

`#`

`# 정의` -- 공간 $(\Omega,{\cal A})$ 를 상상하자. 여기에서 ${\cal A}$는 $\Omega$에 대한 세미링이다. 만약에 어떠한 집합함수 $\tilde{m}: {\cal A} \to [0,\infty]$ with $\tilde{m}(\emptyset) =0$ 이 아래를 만족한다면 

$$\text{$\exists~ \Omega_1,\Omega_2, \dots  \in {\cal F}$ such that (1) $\cup_{i=1}^{\infty}\Omega_i=\Omega$ and (2) $\forall n \in \mathbb{N}: \tilde{m}(\Omega_n)< \infty$}$$ 

$\tilde{m}$을 ${\cal A}$ 에서 $\sigma$-finite 하다고 표현한다. 

`#`


`# 예제1` -- 측도공간 $(\mathbb{R}, {\cal R}, \lambda)$ 를 고려하자. 여기에서 $\lambda$ 는 르벡메저 (즉 길이를 재는 함수), ${\cal R}$ 은 보렐시그마필드 (즉 실수의 부분집합중 길이를 무모순으로 잴 수 있는 집합들의 모임) 이다. 아래가 성립하므로 

$$\lambda(\mathbb{R})=\infty$$

르벡메저는 유한측도가 아니다. 그렇지만 

- $\Omega_1 = [-1,1]$
- $\Omega_2 = [-2,2] - \Omega_1$
- $\Omega_3 = [-3,3] - \Omega_2$
- $\dots$

와 같이 설정한다면, 

$$\forall n \in \mathbb{N}: \lambda(\Omega_n) = 2 <\infty$$ 

가 성립하고 

$$\cup_{i=1}^{\infty}\Omega_i = \Omega = \mathbb{R}$$ 

이므로 르벡메저는 $\sigma$-유한측도이다. 

`#`

:::{.callout-note}
시그마유한 측도의 뉘앙스는 "**전체 집합을 유한한 값으로 나타낼 수는 없을지라도, 전체집합을 쪼개서 (비록 무한번 쪼개는 한이 있더라도), 쪼갠것들은 유한한 값으로 나타낼 수 있는 방법이1 최소한 하나는 존재한다.**" 의 뉘앙스를 가지고 있다. 따라서 시그마측도의 정의에서 집합열 $\Omega_1,\Omega_2,\dots$ 를 무한집합열로 잡을 이유는 굳이 없다. (수 틀리면 무한번 쪼개겠다는 것이지 꼭 무한번 쪼개야 할 이유는 없으니까. 유한번 쪼개서 만들 수 있다면 오히려 좋음!)
:::

`# 예제1의 다른풀이` -- `예제1`에서 $\Omega_1,\Omega_2,\dots$을 아래와 같이 설정해도 된다. 

- $\Omega_1 = [-1,1]$
- $\Omega_2 = [-2,2]$
- $\Omega_3 = [-3,3]$
- $\dots$

그래도 

- $\forall n \in \mathbb{N}: \lambda(\Omega_n) = 2n <\infty$
- $\cup_{i=1}^{\infty}\Omega_i = \Omega = \mathbb{R}$

이 성립하기 때문이다. 

`#`

`# 보충학습` -- $\forall n \in \mathbb{N}: \lambda(\Omega_n) = 2n <\infty$ 이 이상하다면?? 

임의의 자연수 $n$에 대하여 $\frac{1}{n}$는 양수이다. 즉 

$$\forall n \in \mathbb{N}: \frac{1}{n} > 0$$ 

이다. 여기에서 $\mathbb{N}$은 2주차에서 언급한것처럼 $\{\infty\}$ 를 포함하지 않는다. 한편 $\frac{1}{n}$은 아래가 성립한다. 

$$\lim_{n\to \infty} \frac{1}{n} = 0$$ 

정리하면 아래가 성립한다. 

1. $\forall n \in \mathbb{N}: \frac{1}{n} > 0$ 
2. $\lim_{n\to \infty} \frac{1}{n} = 0$ 

여기에서 1에 대해 이해할때는 $n \neq \infty$ 라고 생각하지만 2는 마치 $n=\infty$ 를 대입한듯한 느낌을 줘서 매우 헷갈릴 수 있다. (그렇지만 우리는 헷갈리면 안되죠? 극한을 제대로 이해한 "대학생" 이잖아요?) 유사한 느낌으로 아래도 절대 헷갈리면 안된다. 

1. $\forall n \in \mathbb{N}: \lambda([0,\frac{1}{n}])=\frac{1}{n} > 0$ 
2. $\lim_{n\to \infty} \lambda([0,\frac{1}{n}]) =\lim_{n \to \infty} \frac{1}{n}=0$ 

그리고 아래도.. 

1. $\forall n \in \mathbb{N}: n < \infty$ 
2. $\lim_{n\to \infty} n = \infty$ 

또 아래도.. 


1. $\forall n \in \mathbb{N}: \lambda([0,n])=n < \infty$ 
2. $\lim_{n\to \infty} \lambda([0,n]) =\lim_{n \to \infty} n =\infty$ 

헷갈리면 안된다. 

`#` 

`-` 유한측도이면 $\sigma$-유한측도이다. ($\Omega_1=\Omega$로 잡으면 된다) 따라서 정리하면 아래와 같다. 
$$\text{prob-msr $\Rightarrow$ finite-msr $\Rightarrow$ $\sigma$-finite msr $\Rightarrow$ msr}$$

# 3. 확장이론

## A. 확장이론1 

`# 이론 (카라테오도리의 유산, 확률버전)` --  ${\cal A} \subset 2^{\Omega}$를 $\Omega$에 대한 세미링이라고 하자. ${\cal A}$ 에서 **확률인 듯 확률 아닌** 집합함수 $\tilde{P}:{\cal A} \to [0,1]$ with (1) $\tilde{P}(\emptyset)=0$ and (2) $\tilde{P}(\Omega)=1$ 이 아래의 조건을 만족한다고 가정하자. 

1. **additive on ${\cal A}$**
2. **$\sigma$-subadditive on ${\cal A}$**

이 **확률인 듯 확률 아닌** 함수 $\tilde{P}$는 $\sigma({\cal A})$에서의 확률 $\mathbb{P}$ 로 확장할 수 있다. 그리고 이 확장은 유일하다. 

`#`

`# 이론 (카라테오도리의 유산, $\sigma$-유한측도버전)` --  ${\cal A} \subset 2^{\Omega}$를 $\Omega$에 대한 세미링이라고 하자. ${\cal A}$ 에서 **$\sigma$-유한측도인 듯 $\sigma$-유한측도 아닌** 집합함수 $\tilde{m}:{\cal A} \to [0,\infty]$ with (1) $\tilde{m}(\emptyset)=0$ and (2) $\text{$\tilde{m}$ is $\sigma$-finite on ${\cal A}$}$ 이 아래의 조건을 만족한다고 가정하자. 

1. **additive on ${\cal A}$**
2. **$\sigma$-subadditive on ${\cal A}$**

이 **$\sigma$-유한측도인 듯 $\sigma$-유한측도 아닌** 함수 $\tilde{m}$은 $\sigma({\cal A})$에서의 $\sigma$-유한측도로 확장될 수 있다. 그리고 이 확장은 유일하다. 

`#`

:::{.callout-warning}
이 이론은 **확률인 듯 확률 아닌** 함수, **유한측도인 듯 유한측도 아닌** 함수, **$\sigma$-유한측도인 듯 $\sigma$-유한측도 아닌** 함수에는 성립하지만 **측도인 듯 측도 아닌**함수에 대해서는 성립하지 않음. 
:::

`# 예제1`

$\Omega=\{1,2,3,4\}$이라고 하자. 내가 관심있는 집합의 모음 (=내가 확률을 정의하고 싶은 이벤트들의 모음) 은 아래와 같다. 

$${\cal A} = \{\emptyset, \{1\},\{2\},\{3,4\},\Omega\}$$

이러한 집합에서 아래와 같은 함수를 정의하자. 

- $\tilde{P}(\emptyset) = 0$
- $\tilde{P}(\{1\}) = 1/4$
- $\tilde{P}(\{2\}) = 1/2$
- $\tilde{P}(\{3,4\}) = 1/4$
- $\tilde{P}(\Omega) = 1$

아쉽게도 ${\cal A}$는 시그마필드의 정의를 만족하지 않으므로, 위와 같은 함수 $\tilde{P}$를 확률(=확률측도)이라고 주장할 수 없다.^[그렇지만 사실 딱봐도 확률 같은걸? 이 정도만 정의하면 $\sigma({\cal A})$ 에서의 모든 사건들은 알아서 센스있게 잘 정의될 것 같은걸?] 그렇다고 해서 $\sigma({\cal A})$를 구한 다음 그 위에서 확률측도를 정의하는건 너무 귀찮은 일이다. 어쩌면 좋을까? 

`(풀이)`

${\cal A}$는 세미링이고 $\tilde{P}$는 ${\cal A}$에서 (1) additivity (2) $\sigma$-subadditivity 를 만족한다. 

:::{.callout-note}

### add 체크~ 

우선 add를 체크하기 위해서 아래를 만족하는 집합 $A, A_1, A_2, \dots, A_M \in {\cal A}$ 가 있는지 살펴본다. 
$$A =\biguplus_{n=1}^{M}A_n$$

이러한 조건을 만족하는 집합은 
$$\Omega = \{1\} \uplus \{2\} \uplus \{3,4\}$$ 

밖에 없다. 따라서 위의 case에 대한 additivity를 체크하기만 하면 된다. 양변에 $\tilde{P}$를 취하면 

$$1 = \tilde{P}(\{1\})+ \tilde{P}(\{2\}) + \tilde{P}(\{3,4\})=\frac{1}{4}+\frac{1}{2}+\frac{1}{4}$$ 

이 되므로 $\tilde{P}$는 ${\cal A}$ 에서 additivity를 만족한다. 
:::

:::{.callout-note}

### $\sigma$-subadd 체크~ 

${\cal A}$의 cardinality는 finite 하므로 $\sigma$-subadd 를 체크할 필요 없이 subadd 만 체크하면 된다. 그런데 add 는 subadd를 imply 하므로 체크할 필요가 없다. 
:::

따라서 $\big(\Omega,{\cal A},\tilde{P}\big)$ 를 확장하여 measure space $\big(\Omega,\sigma({\cal A}),\mathbb{P}\big)$ 로 만들 수 있다. 또한 이러한 확장은 유일하다. 즉 아래가 성립한다. 

$$
\text{$\exists! \mathbb{P}$ such that (1) $\mathbb{P}$ is prob-msr on $\big(\Omega, \sigma({\cal A})\big)$ (2) $\forall A \in {\cal A}: \mathbb{P}(A) = \tilde{P}(A)$}
$$

따라서 ${\cal A}=\{\emptyset, \{1\}, \{2\}, \{3,4\}, \Omega\}$ 에서의 집합함수 

- $\tilde{P}(\emptyset) = 0$
- $\tilde{P}(\{1\}) = 1/4$
- $\tilde{P}(\{2\}) = 1/2$
- $\tilde{P}(\{3,4\}) = 1/4$
- $\tilde{P}(\Omega) = 1$

만 정의해도, 확률을 정의한 셈 칠 수 있다!

`#`

`# 예제2`

$\Omega=\{1,2,3,4\}$이라고 하고 ${\cal A} = \{\emptyset, \{1\},\{2\}, \{3,4\}, \Omega\}$ 라고 하자. 그리고 아래와 같은 $\sigma({\cal A})$를 다시 상상하자. 

$$\sigma({\cal A}) = \big\{\emptyset, \{1\}, \{2\}, \{1,2\}, \{3,4\}, \{1,3,4\}, \{2,3,4\}, \Omega \big\}$$

위의 시그마필드에서 확률을 예제1과 다른 방식으로 정의할 수 도 있다. 예를들면 아래와 같은 방식으로 정의가능하다. 

||$\mathbb{P}_1$|$\tilde{P}_1$|
|:-:|:-:|:-:|
|$\emptyset$|$0$|$0$|
|$\{1\}$|$\frac{1}{3}$ | $\frac{1}{3}$| 
|$\{2\}$|$\frac{1}{3}$ | $\frac{1}{3}$| 
|$\{3,4\}$|$\frac{1}{3}$ | $\frac{1}{3}$| 
|$\Omega$|$1$ | $1$|
|$-$|$-$|$-$|
|$\{1,2\}$|$\frac{2}{3}$ | None|
|$\{1,3,4\}$|$\frac{2}{3}$ | None|
|$\{2,3,4\}$|$\frac{2}{3}$ | None |

또한 아래와 같은 방식도 가능하다. 

||$\mathbb{P}_2$|$\tilde{P}_2$|
|:-:|:-:|:-:|
|$\emptyset$|$0$|$0$|
|$\{1\}$|$0$ | $0$| 
|$\{2\}$|$0$ | $0$| 
|$\{3,4\}$|$1$ | $1$| 
|$\Omega$|$1$ | $1$|
|$-$|$-$|$-$|
|$\{1,2\}$|$0$ | None|
|$\{1,3,4\}$|$1$ | None|
|$\{2,3,4\}$|$1$ | None |

어떠한 방식으로 정의하든 ${\cal A}$ 에서 **확률인 듯 확률 아닌** $\tilde{P}_1,\tilde{P}_2$ 를 잘 정의하기만 $\sigma({\cal A})$ 에서의 확률 $\mathbb{P}$ 로 적절하게 확장할 수 있다. 심지어 이러한 확장은 유일하다. 

`#`

`# 예제3`

$\Omega = \{a,b,c,d\}$ 의 부분집합들의 모임 

$${\cal A}=\big\{\{a,b,c\},\{b,c,d\}\big\}$$ 

를 고려하자. **확률인 듯 확률 아닌** 함수 $\tilde{P}: {\cal A} \to [0,1]$ 을 아래와 같이 정의하자. 

- $\tilde{P}(\{a,b,c\}) = \frac{3}{4}$
- $\tilde{P}(\{b,c,d\}) = \frac{3}{4}$

$\tilde{P}$ 를 확장하여 확률측도의 정의를 만족하는 적당한 함수 $\mathbb{P}:\sigma({\cal A}) \to [0,1]$ 를 유일하게 만들 수 있는가?

`(풀이)`

${\cal A}$는 세미링이 아니므로 확장정리를 쓸 수 없다. 그렇지만 ${\cal A}$를 변형하여 아래를 만든다면 

$$\bar{\cal A} = \big\{\{a,b,c\},\{b,c,d\}, \emptyset, \Omega, \{b,c\}, \{a\}, \{d\}\big\}$$

$\bar {\cal A}$ 는 세미링이 된다. 이제 **확률 인듯 확률 아닌 함수** $\bar{P}: \bar{\cal A} \to [0,1]$ 를 고려하자.

- $\tilde{P}(\{a,b,c\}) = \bar{P}(\{a,b,c\}) = \frac{3}{4}$
- $\tilde{P}(\{b,c,d\}) = \bar{P}(\{b,c,d\}) = \frac{3}{4}$
- $\bar{P}(\emptyset) = 0$
- $\bar{P}(\Omega) = 1$
- $\bar{P}(\{a\}) = \frac{1}{4}$
- $\bar{P}(\{d\}) = \frac{1}{4}$
- $\bar{P}(\{b,c\}) = \frac{1}{2}$

$\bar{P}$는 $\tilde{P}$를 확장한 **확률인 듯 확률 아닌 함수**이다. 즉 $\bar{P}$는 $\bar{\cal A}$ 에서 (1) additivity (2) $\sigma$-subadditivity 를 만족한다.^[add 만 체크하면 끝나는거 알죠?] 따라서 $\bar{P}$를 확장하여 $\sigma(\bar{A})=\sigma({\cal A})$에서의 확률 $\mathbb{P}$를 만들 수 있으며, 이렇게 만들어진 $\mathbb{P}$는 유일하다. 또한 $\tilde{P}$를 확장하여 $\bar{\cal A}$에서의 **확률인 듯 확률 아닌 함수**로 확장하는 방법이 $\bar{P}$가 유일함을 떠올리면^[$\bar{P}(\emptyset)$, $\bar{P}(\Omega)$, $\bar{P}(\{a\})$, $\bar{P}(\{d\})$, $\bar{P}(\{b,c\})$의 값을 달리 정의할 수 있는 방법이 없잖아요??] ${\cal A}$에서의 집합함수 $\tilde{P}$를 $\sigma({\cal A})$에서의 확률로 업그레이드 하는 방법은 이것이 유일함을 알 수 있다. 

:::{.callout-warning}
사실 $\tilde{P}$를 확장하여 $\bar{\cal A}$에서의 **확률인 듯 확률 아닌 함수**로 확장하는 방법이 $\bar{P}$가 유일하다는 논리는 약간 어설퍼보임. 이것은 뒤에 확장이론2를 이해하면 더 깔끔해짐. 
:::

`#`

`# 예제4` 

$\Omega=\{1,2,3\}$ 이라고 하고 ${\cal A} = \{\emptyset, \{1,2\},\{2,3\}, \Omega\}$ 라고 하자. 아래와 같은 집합함수 $\tilde{P}:{\cal A} \to [0,1]$를 정의하자.

- $\tilde{P}(\emptyset) = 0$
- $\tilde{P}(\{1,2\}) = 0$
- $\tilde{P}(\{2,3\}) = 0$
- $\tilde{P}(\Omega) = 1$

일단 ${\cal A}$는 세미링이 아니다. 따라서 확장정리를 바로 적용할 수 없다. 적당히 ${\cal A}$를 확장하여 세미링 $\bar{\cal A}$를 만든다고 하여도 $\bar{\cal A}$에서 subadditivity가 성립하지 않는다. 즉 **확률인 듯 확률 아닌** 함수조차 만들 수 없다. 따라서 이 경우는 확장이 불가능하다. 

`#`

`# 예제5` 

$\Omega=\{1,2,3,4\}$ 이라고 하고 ${\cal A} = \{\emptyset, \{1,2\},\{2,3\}, \Omega\}$ 라고 하자. 아래와 같은 확률 비슷한 함수 $\tilde{P}:{\cal A} \to [0,1]$를 정의하자.

- $\tilde{P}(\emptyset) = 0$
- $\tilde{P}(\{1,2\}) = 1/2$
- $\tilde{P}(\{2,3\}) = 1/2$
- $\tilde{P}(\Omega) = 1$

이 예제의 경우 위의 예제와 다르게 $\bar{\cal A}$에서 subadditivity가 성립해보인다. 확장을 시도해보자. 우선 ${\cal A}$를 적당히 확장하여 세미링을 만든다. 
$$\bar{\cal A} = \{\emptyset, \{1,2\}, \{2,3\}, \Omega, \{1\}, \{2\}, \{3\}, \{4\}\}$$

이제 $\tilde{P}$를 적절히 확장하여 **확률인 듯 확률 아닌** 함수 $\bar{P}: \bar{\cal A} \to [0,1]$ 를 정의해보자. 그런데... 

||$\bar{P}_1$|$\bar{P}_2$|
|:-:|:-:|:-:|
|$\emptyset$|$0$|$0$|
|$\{1,2\}$|$1/2$ | $1/2$| 
|$\{2,3\}$|$1/2$ | $1/2$| 
|$\Omega$|$1$ | $1$|
|$-$|$-$|$-$|
|$\{1\}$|$0$ | $1/2$ |
|$\{2\}$|$1/2$ |$0$ |
|$\{3\}$|$0$ | $1/2$ |
|$\{4\}$|$1/2$ | $0$ |

와 같이 유일하게 $\bar{P}$를 정할 수 없다. 이때 위에서 정의된 함수 $\tilde{P}_1$, $\tilde{P}_2$ 는 모두 세미링 $\bar{\cal A}$ 에서 (1) additivity (2) $\sigma$-additivity 를 만족한다.^[add만 체크해도 되는거 아시죠?] 따라서 **확률인 듯 확률 아닌** 함수 $\tilde{P}_1$, $\tilde{P}_2$ 는 각각 확률 $\mathbb{P}_1$, $\mathbb{P}_2$로 업그레이드 될 수 있다. 요약하면 $\tilde{P}$는 확장되어 확률 $\mathbb{P}_1$ 로 업그레이드 될 수도 있고 $\mathbb{P}_2$ 로 업그레이드 될 수도 있다. 따라서 일단 $\tilde{P}$ 는 업그레이드는 가능하지만 그 결과가 유일하지 않다고 볼 수 있다. 

`#`

`# 예제6` -- 통계학과라서 행복해 

$\Omega=\{a,b\}$ 이라고 하고 ${\cal A} = \{\emptyset,\{a\}\}$ 라고 하자. 여기에서 ${\cal A}$ 는 세미링이다. 이때 **측도인 듯 측도 아닌** 함수 $\tilde{m}: {\cal A} \to [0,1]$ 를 아래와 같이 정의하자. 

- $\tilde{m}(\emptyset)=0$ 
- $\tilde{m}(\{a\})=\frac{1}{2}$ 

그렇지만 잴 수 있는 공간 $(\Omega,\sigma({\cal A})\big)$에서 정의가능한 "측도" $m$은 ${\cal A}$에서의 값으로 유일하게 결정되지 않는다.^[그렇지만 우리가 알바는 아님]

||$m_1$|$m_2$|
|:-:|:-:|:-:|
|$\{a\}$|$\frac{1}{2}$ | $\frac{1}{2}$|
|$-$|$-$|$-$|
|$\emptyset$|$0$|$0$|
|$\{b\}$|$\frac{1}{2}$|$1$|
|$\Omega$|$1$|$\frac{3}{2}$|

`#`

**`# 예제7`** -- 르벡메저($\star\star\star$) 

$\Omega=\mathbb{R}$ 이라고 하고 

$${\cal A} = \big\{(a,b]: -\infty<a<b<\infty \big\} \cup \{\emptyset\}$$

라고 하자. 여기에서 ${\cal A}$는 세미링이다. 이때 $\bar{\cal A}$에서 **$\sigma$-유한측도인 듯 $\sigma$-유한측도 아닌** 함수 $\tilde{\lambda}: {\cal A} \to [0,1]$, $\tilde{\lambda}(\emptyset)=0$ 를 아래와 같이 정의하자. 
$$\tilde{\lambda}((a,b])=b-a$$

이제 $\tilde{\lambda}$가 ${\cal A}$에서 (1) additivity (2) $\sigma$-additivity 를 만족한다면 $\tilde{\lambda}$는 잴 수 있는 공간 $\big(\Omega, \sigma({\cal A})\big)=(\mathbb{R}, {\cal R})$ 에서의 측도로 업그레이드 되며 이 업그레이드 결과는 유일하다. 그리고 이러한 방식으로 업그레이드된 척도를 르벡척도라고 한다. 

이 예제에서 남은 부분은 $\tilde{\lambda}$가 ${\cal A}$에서 (1) additivity (2) $\sigma$-additivity 를 만족함을 보이는 것이다. 이때 additivity가 성립함은 자명하고, $\sigma$-subadditivity가 성립함을 보여야 하는데 이것은 매우 어렵다. 따라서 이 예제에서는 생략하겠다. (안할건 아니고요, 다음에 할거에요..)

`#`

:::{.callout-note}

### 지금까지의 스토리 

1. $\Omega$의 모든 부분집합에 대하여 확률을 **무모순**으로 정의하는 것은 매우 쉬운일인 줄 알았는데 사실은 그렇지 않았다. 
2. 그 이유는 $\mathbb{R}$의 모든 부분집합에 길이를 **무모순**으로 재는 것이 불가능하기 때문이다. 
3. 우리는 $\mathbb{R}$의 모든 부분집합, $2^\Omega$에 대하여 길이를 **무모순**으로 재는 것은 포기하였다. 대신에 그것보다 작은 집합 ${\cal R} \subset 2^{\Omega}$ 보렐시그마필드(=길이를 잴 수 있는 집합들의 모임)에서만 길이를 재는것이 어떨까? 하는 생각을 했다. 여기에서 ${\cal R}$은 $${\cal A}=\big\{(a,b]: -\infty<a<b<\infty \big\} \cup \{\emptyset\}$$를 확장하여 만들 수 있는 가장 작은 시그마필드이다.
4. 우리의 전략은 ${\cal A}$ 에서 **길이인 듯 길이 아닌** 함수 $\tilde{\lambda}$ 를 정의하고 그 함수를 확장하여 메저로 업그레이드 하는 것이었다. 이를 위해서 측도론이라는 학문을 공부했다. 공부한결과 카라테오도리의 유산에 의하여 이러한 업그레이드방식이 가능하며, 심지어 그 결과가 유일하다는 것을 알게 되었다.

:::

## B. 확장이론2

`-` 르벡메저를 드디어 정의했는데, 사실 조금 찝찝한 부분이 있다. 

:::{.callout-note}

### 르벡메저에 대한 불만

왜 하필 아래와 같은 집합에서만 **길이인 듯 길이 아닌** 함수를 정의한뒤 그것을 확장해야 하지? 
$${\cal A}_1=\big\{(a,b]: -\infty<a<b<\infty \big\} \cup \{\emptyset\}$$

예를들어서 아래의 집합에서 정의하면 안되나? 

- ${\cal A}_2=\big\{[a,b): -\infty<a<b<\infty \big\} \cup \{\emptyset\}$
- ${\cal A}_3=\big\{[a,b]: -\infty<a<b<\infty \big\} \cup \{\emptyset\}$
- ${\cal A}_4=\big\{(a,b): -\infty<a<b<\infty \big\} \cup \{\emptyset\}$

그리고 어떠한 집합에서 정의하여 확장하든 다 같은 **길이**아닌가?

----

아래가 성립함은 알고 있다.

- ${\cal A}_1$ 에서 정의된 **길이인 듯 길이 아닌** 함수 $\tilde{\lambda}_1((a,b]) = b-a$ 는 잴 수 있는 공간 $(\mathbb{R},{\cal R})$ 에서의 길이 $\lambda_1=\lambda$로 업그레이드 가능하며, 그 결과는 유일하다. 

이제 아래가 된다는 것을 보이고 싶다. 

- ${\cal A}_2$ 에서 정의된 **길이인 듯 길이 아닌** 함수 $\tilde{\lambda}_2([a,b)) = b-a$ 는 잴 수 있는 공간 $(\mathbb{R},{\cal R})$ 에서의 길이로 업그레이드 가능하며, 그 결과는 $\lambda_1$와 동일하다. (이 경우 확장은 가능함.)
- ${\cal A}_3$ 에서 정의된 **길이인 듯 길이 아닌** 함수 $\tilde{\lambda}_3([a,b]) = b-a$ 는 잴 수 있는 공간 $(\mathbb{R},{\cal R})$ 에서의 길이로 업그레이드 가능하며, 그 결과는 $\lambda_1$와 동일하다. 
- ${\cal A}_4$ 에서 정의된 **길이인 듯 길이 아닌** 함수 $\tilde{\lambda}_4((a,b)) = b-a$ 는 잴 수 있는 공간 $(\mathbb{R},{\cal R})$ 에서의 길이로 업그레이드 가능하다, 그 결과는 $\lambda_1$와 동일하다. 

:::

`-` 위의 불만을 해결하기 위해서 ${\cal A}_2$, ${\cal A}_3$, ${\cal A}_4$를 적당히 확장 혹은 축소하여 ${\cal A}_1$로 바꾸고 $\tilde{\lambda}_2$, $\tilde{\lambda}_3$, $\tilde{\lambda}_4$ 를 적당히 변경하여 $\tilde{\lambda}_1$으로 바꾸는 방법이 유일하다는 것을 보이면, 확장이론1의 `예제3` 와 같은 논리전개로 해결할 수 있다. **그런데 이 논리가 좀 약해보임.**


**`# 이론 (확장이론2)`** -- *확장의 존재성이 보장될때 유일성을 보이는 테크닉*

${\cal A}$가 $\Omega$에 대한 파이시스템일때, 잴 수 있는 공간 $\big(\Omega, \sigma({\cal A})\big)$에서의 $\sigma$-유한측도 $m$은 ${\cal A}$에서의 값으로 **유일하게 결정된다**. 즉 ${\cal A}$ 에서는 그 값이 일치하지만, $\sigma({\cal A})$ 에서는 일치하지 않는 두개의 $\sigma$-유한측도 $m_1$,$m_2$는 존재할 수 없다. 

`#`

:::{.callout-warning}
확장이론1은 "확장의 존재성 & 유일성"을 동시에 보장한다. 그런데 확장이론2는 "유일성"만을 보장한다. 확장이론1은 "존재성" 보이는것이 매우 어려운 경우 유용하다. (예를들면 르벡메저의 경우) 확장이론1의 논리전개는 $\big(\Omega, {\cal A}\big)$ 에서 additivity, sub-additivity 를 체크해야하는 방향으로 흐른다. 확장이론2는 "존재성" 보장되는 상황에 "유일성"을 보이는 것이다. 따라서 일단 확장된 공간 $\big(\Omega,\sigma({\cal A})\big)$ 에서 측도 하나를 어떻게는 "설정"해놓고 그 설정값이 유일하다는 식의 주장을 하는 논리전개를 따른다. 
:::

**`# 예제1`** -- 확장이론2의 위대함을 보여줄게요..

$\Omega=\{1,2,3,4\}$이라고 하자. 내가 관심있는 집합의 모음 (=내가 확률을 정의하고 싶은 이벤트들의 모음) 은 아래와 같다. 

$${\cal A} = \{\emptyset, \{1\},\{2\},\{3,4\},\Omega\}$$

이러한 집합에서 아래와 같은 함수를 정의하자. 

- $\tilde{P}(\emptyset) = 0$
- $\tilde{P}(\{1\}) = 1/4$
- $\tilde{P}(\{2\}) = 1/2$
- $\tilde{P}(\{3,4\}) = 1/4$
- $\tilde{P}(\Omega) = 1$

아쉽게도 ${\cal A}$는 시그마필드의 정의를 만족하지 않으므로, 위와 같은 함수 $\tilde{P}$를 확률(=확률측도)이라고 주장할 수 없다.^[그렇지만 사실 딱봐도 확률 같은걸? 이 정도만 정의하면 $\sigma({\cal A})$ 에서의 모든 사건들은 알아서 센스있게 잘 정의될 것 같은걸?] 그렇다고 해서 $\sigma({\cal A})$를 구한 다음 그 위에서 확률측도를 정의하는건 너무 귀찮은 일이다. 어쩌면 좋을까? 

`(풀이1)` -- 확장이론1 적용

아까 한 풀이.. ${\cal A}$이 세미링임을 체크하고 $\tilde{P}$ 가 (1) additive in ${\cal A}$ (2) $\sigma$-subadditive on ${\cal A}$ 임을 보임. 

`(풀이2)` -- 확장이론2 적용

아래표의 오른쪽과 같은 $\sigma({\cal A})$에서의 확률측도 $\mathbb{P}$를 일단 만들어보자. 

||$\tilde{P}$|$\mathbb{P}$|
|:-:|:-:|:-:|
|$\emptyset$|$0$|$0$|
|$\{1\}$|$\frac{1}{4}$ |$\frac{1}{4}$ |
|$\{2\}$|$\frac{1}{4}$ |$\frac{1}{2}$ |
|$\{3,4\}$|$\frac{1}{4}$ |$\frac{1}{4}$ |
|$\Omega$|$1$ |$1$ |
|$-$|$-$|$-$|
|$\{1,2\}$| |$\frac{3}{4}$ |
|$\{1,3,4\}$| |$\frac{1}{2}$ |
|$\{2,3,4\}$| |$\frac{3}{4}$ |

심심풀이로 $\tilde{P}$를 확장한 확률측도 $\mathbb{P}$를 만들어 봤는데, 이 확률측도는 유일하다. 왜냐하면 ${\cal A}$가 파이시스템이니까.. 

:::{.callout-note}

### 혹시 위의 state가 잘 이해 안된다면..

왜 유일한지 따지기 위해 일단 유일하지 않다고 가정하자. (귀류법) 그렇다면 ${\cal A}$ 에서는 일치하지만 $\sigma({\cal A})$ 에서는 일치하지 않는 서로 다른 두개의 측도 $\mathbb{P}_1$, $\mathbb{P}_2$ 가 존재한다는 의미이다. 즉 아래가 성립한다. 
$$\text{$\exists$ prob-msr $\mathbb{P}_1, \mathbb{P}_2$ on $\sigma({\cal A})$ such that (1) $\forall A \in {\cal A}:~ \mathbb{P}_1(A) = \mathbb{P}_2(A)$, while (2) $\forall B \in \sigma({\cal A}):~\mathbb{P}_1(B) \neq \mathbb{P}_2(B)$}.$$

그런데 ${\cal A}$는 파이시스템이므로 확장이론2를 쓸 수 있는데, 확장이론2에 따르면 위의 정리는 불가능하다. (모순)
:::

`#` 

**`# 예제2`** 

$\Omega=\{1,2,3,4\}$ 이라고 하고 ${\cal A} = \{\emptyset, \{1,2\},\{2,3\}, \Omega\}$ 라고 하자. 이제 $\sigma({\cal A})$ 에서의 확률측도 $\mathbb{P}_1$ 와 $\mathbb{P}_2$ 를 고려하자. 

||$\mathbb{P}_1$|$\mathbb{P}_2$|
|:-:|:-:|:-:|
|$\emptyset$|$0$|$0$|
|$\{1,2\}$|$\frac{1}{2}$ | $\frac{1}{2}$|
|$\{2,3\}$|$\frac{1}{2}$ | $\frac{1}{2}$|
|$\Omega$|$1$ | $1$|
|$-$|$-$|$-$|
|$\{1\}$|$0$ | $\frac{1}{2}$|
|$\{2\}$|$\frac{1}{2}$ | $0$|
|$\{3\}$|$0$ | $\frac{1}{2}$|
|$\{4\}$|$\frac{1}{2}$ | $0$|
|$\{1,3\}$|$0$ | $1$| 
|$\{1,4\}$|$\frac{1}{2}$ | $\frac{1}{2}$|
|$\{2,4\}$|$1$ | $0$|
|$\{3,4\}$|$\frac{1}{2}$ | $\frac{1}{2}$|
|$\{2,3,4\}$|$1$ | $\frac{1}{2}$|
|$\{1,3,4\}$|$\frac{1}{2}$ | $1$|
|$\{1,2,4\}$|$1$ | $\frac{1}{2}$|
|$\{1,2,3\}$|$\frac{1}{2}$ | $1$|

여기에서 $\mathbb{P}_1$와 $\mathbb{P}_2$는 분명히 ${\cal A}$에서는 일치하지만, $\sigma({\cal A})$ 에서는 일치하지 않는다. 즉 $\big(\Omega, \sigma({\cal A})\big)$ 에서의 모든 확률측도의 값은 ${\cal A}$ 에서의 값으로 유일하게 결정되지는 않는다. 

그 이유는 여기에서 주어진 ${\cal A}$가 파이시스템이 아니기 때문이다. 따라서 ${\cal A}$에서의 값은 agree하지만 $(\Omega, \sigma({\cal A}))$에서 agree하지 않는 서로 다른 확률측도가 존재할 수도 있는 것이다. 만약에 이 예제에서 ${\cal A}$를 아래와 같이 수정한다면 

$${\cal A}=\{\emptyset, \{1,2\}, \{2,3\}, \{2\}\}$$

이번에는 ${\cal A}$는 파이시스템이 된다. 따라서 이 경우 $(\Omega, \sigma({\cal A}))$에서의 모든 확률측도는 ${\cal A}$의 값에 의하여 유일하게 결정된다. 

`#` 


**`# 예제3`** 

$\Omega = \{a,b,c,d\}$ 의 부분집합들의 모임 

$${\cal A}=\big\{\{a,b,c\},\{b,c,d\}\big\}$$ 

를 고려하자. **확률인 듯 확률 아닌** 함수 $\tilde{P}: {\cal A} \to [0,1]$ 을 아래와 같이 정의하자. 

- $\tilde{P}(\{a,b,c\}) = \frac{3}{4}$
- $\tilde{P}(\{b,c,d\}) = \frac{3}{4}$

$\tilde{P}$ 를 확장하여 확률측도의 정의를 만족하는 적당한 함수 $\mathbb{P}:\sigma({\cal A}) \to [0,1]$ 를 유일하게 만들 수 있는가?

`(풀이)` -- 아마 이렇게 풀고 싶었을 거에요. 

$\sigma({\cal A})$를 구하면 아래와 같다. 

$$\sigma({\cal A})=\big\{\{a,b,c\},\{b,c,d\},\emptyset,\Omega, \{d\},\{a\},\{a,d\},\{b,c\}\big\}$$

$\tilde{P}$를 확장한 확률측도를 하나 만들어보자. 

||$\mathbb{P}$|
|:-:|:-:|:-:|
|$\{a,b,c\}$|$\frac{3}{4}$ |
|$\{b,c,d\}$|$\frac{3}{4}$ |
|$-$|$-$|
|$\emptyset$|$0$|
|$\Omega$|$1$ |
|$\{d\}$|$\frac{1}{4}$
|$\{a\}$|$\frac{1}{4}$
|$\{a,d\}$|$\frac{2}{4}$
|$\{b,c\}$|$\frac{2}{4}$

만들면서 생각한 **느낌적인 느낌**은 저런방식 이외로 확장하는 방법이 없겠다는 것이다. 하지만 그 "**느낌**"이 유일성을 "**증명**"하는 것은 아니다. 유일성을 증명하기 위해서 아래와 같은 집합 $\bar{\cal A}$ 를 생각하자. 

$$\bar{\cal A} = \big\{ \{a,b,c\},\{b,c,d\},\{b,c\} \big\}$$

$\bar{\cal A}$는 파이시스템이다. 따라서 $\big(\Omega, \sigma({\cal A})\big)$ 에서의 모든 확률측도는 $\bar{\cal A}$ 에서의 값으로 유일하게 결정된다. 

`#`

**`# 예제3`** -- 르벡메져

어떠한 경로로 인하여 보렐시그마필드 ${\cal R}$ 와 르벡메저 $\lambda$ 의 존재성을 배웠다고 치자. 그렇다면 measure space $(\mathbb{R}, {\cal R}, \lambda)$ 선언할 수 있다. 관심 있는 집합들의 모임 ${\cal A} = \big\{(a,b):-\infty < a <b < \infty \big\}$에 대하여 아래와 같은 집합함수 $\tilde{\lambda}: {\cal A} \to [0,\infty]$ 를 생각하자. 

$$\tilde{\lambda}((a,b)) = b-a$$ 

아래의 사실을 체크하자. 

1. $\forall A \in {\cal A}:~ \lambda(A) = \tilde{\lambda}(A)$ 이다. 
2. ${\cal A}$ 는 파이시스템이다. 

확장이론2에 따라서 $\tilde{\lambda}$ 는 $\lambda$ 로 밖에 확장될 수 없다. 이 예제에서 ${\cal A}$ 를 아래중 어떠한 방식으로 정의해도 동일한 논리가 성립한다. 

- ${\cal A}= \big\{[a,b]:-\infty < a <b < \infty \big\}$
- ${\cal A}= \big\{[a,b):-\infty < a <b < \infty \big\}$
- ${\cal A}= \big\{(a,b]:-\infty < a <b < \infty \big\}$

> ${\cal A}$를 정의할때 공집합이 빠져도 된다는 사실도 우리에게 즐거움을 준다. ${\cal A}$가 파이시스템이면 되었지, 세미링일 필요까진 없으니까..

`#`

:::{.callout-tip}
확률을 정의할 때 엄밀하게 정의한답시고 시그마필드에서 정의하는건 원래 말도 안되는 일이에요. 적당히 세미링이나 파이시스템에서만 정의해도 충분히 엄밀하다 생각하고 넘어갈 수 있습니다. 예를들어 "공평한 동전"이 만드는 확률을 기술하고자 할때 

> 표본공간 $\Omega=\{H, T\}$에서, 앞면이 나올 확률이 $\mathbb{P}(\{H\})=\frac{1}{2}$인 동전 던지기 상황을 생각해보자.

정도로 서술하면 되는 것이지 

> 표본공간 $\Omega=\{H, T\}$를 고려하자. 이때, ${\cal F}=\{\emptyset, \{T\}, \{H\}, \Omega\}$가 $\Omega$에 대한 시그마 필드라고 하자. 또한, 확률은 $\mathbb{P}(\emptyset)=0$, $\mathbb{P}(\{H\})=\frac{1}{2}$, $\mathbb{P}(\{T\})=\frac{1}{2}$, $\mathbb{P}(\Omega)=1$로 정의되는 동전 던지기 상황을 생각해보자.

와 같이 서술하는건 일반적인 서술방법은 아닙니다. 파이시스템인 ${\cal A}=\{\{H\}\}$ 에서 확률값 $\mathbb{P}(\{H\})=\frac{1}{2}$ 만을 **잘** 정의해도, $\sigma({\cal A}) = {\cal F}$ 에서의 확률값이 자동결정된다는 점을 알고 있기 때문입니다. 

:::


